### ISSUE TITLE
inplace_abn usage

### ISSUE THREAD

**Issue by kisialiou** [Serge-weihao/CCNet-Pure-Pytorch#13]
Hi,
thank you a lot for your implementation. I'd like to clarify one moment.

In README file you state that you decided not to use Cuda  inplace-abn. However, there're number of imports from inplace_abn (e.g. in networks/ccnet.py) which are used further. What should I do with them?

Thank you in advance!

**Comment by Serge-weihao** [comment]
![image](https://user-images.githubusercontent.com/40890323/111764215-f1c06580-88dd-11eb-9063-5caee3bae04c.png)
![image](https://user-images.githubusercontent.com/40890323/111765094-ecafe600-88de-11eb-95fc-a90503e41f67.png)

Those are not implemented by the program obviously. You can removed them directly. checkpoint in pytorch is very convenient, so the inplace_abn is not necessary now.

**Comment by kisialiou** [comment]
Surely, I confused it with the original repository! Thanks a lot!
