### ISSUE TITLE
About 3d version

### ISSUE THREAD

**Issue by Limingxing00** [Serge-weihao/CCNet-Pure-Pytorch#19]
Hi,

I am concerned about ```CrissCrossAttention3D```,  ```CrissCrossAttention3D1 ``` and  ```CrissCrossAttention3D2 ``` in [cc3d.py](https://github.com/Serge-weihao/CCNet-Pure-Pytorch/blob/master/networks/CC3d.py).  What is the difference between them? 

Specifically, I am not sure what INF3D will affect them?

**Comment by Serge-weihao** [comment]
mathematically equivalent, but implemented in a different way.  They may have small numerical differences for certain inputs.

**Comment by Limingxing00** [comment]
Thank you!
