### ISSUE TITLE
Apex error

### ISSUE THREAD

**Issue by Srutsth** [Serge-weihao/CCNet-Pure-Pytorch#8]
It is stated that if we do not need either Cuda extension or apex. And we can run only from python 3 and pytorch.
But, when I began used "python train.py --data-dir /data/datasets/Cityscapes/ --random-mirror --random-scale --restore-from ./dataset/resnet101-imagenet.pth --gpu 0,1,2,3 --learning-rate 0.01 --input-size 769,769 --weight-decay 0.0001 --batch-size 4 --num-steps 60000 --recurrence 2 --ohem 1 --ohem-thres 0.7 --ohem-keep 100000 --model ccnet
"

It gave this error stating apex is needed.
Traceback (most recent call last):
  File "/home/shrutisth/PycharmProjects/CCNet-Pure-Pytorch/engine.py", line 19, in <module>
    from apex.parallel import DistributedDataParallel, SyncBatchNorm
ModuleNotFoundError: No module named 'apex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    from engine import Engine
  File "/home/shrutisth/PycharmProjects/CCNet-Pure-Pytorch/engine.py", line 22, in <module>
    "Please install apex from https://www.github.com/nvidia/apex .")
ImportError: Please install apex from https://www.github.com/nvidia/apex .

**How can we use this repo without CUDA extension and apex?**

**Comment by Serge-weihao** [comment]
you can remove from "from apex.parallel import DistributedDataParallel, SyncBatchNorm" and sentences included "DistributedDataParallel", because you do not use DistributedDataParallel.
or you can replace 
"
try:
    from apex.parallel import DistributedDataParallel, SyncBatchNorm
except ImportError:
    raise ImportError(
        "Please install apex from https://www.github.com/nvidia/apex .")
"
with
"
from torch.nn.parallel import DistributedDataParallel
"
